# Generated by Django 5.1.1 on 2024-10-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons_DB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название')),
                ('title_en', models.CharField(max_length=100, verbose_name='Название(англ.)')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('skill_needed', models.CharField(max_length=80, verbose_name='Навык')),
                ('damage_1_shot', models.CharField(max_length=50, verbose_name='Урон 1-го выстрела')),
                ('standard_mag', models.CharField(max_length=50, verbose_name='Стандар. магазин')),
                ('ammo_type', models.CharField(max_length=80, verbose_name='Патроны')),
                ('rate_of_fire', models.CharField(max_length=50, verbose_name='СКА')),
                ('hands_needed', models.CharField(max_length=50, verbose_name='Кол-во рук')),
                ('able_to_hide', models.BooleanField(default=False, verbose_name='Можно скрыть?')),
                ('price', models.CharField(max_length=50, verbose_name='Цена(низкое/обычное/отличное качество')),
                ('price_category', models.CharField(max_length=80, verbose_name='Ценовая категория')),
                ('features', models.TextField(verbose_name='Свойства')),
                ('description', models.TextField(verbose_name='Описание')),
                ('source', models.CharField(default='КорБук', max_length=100, verbose_name='Источник')),
            ],
        ),
    ]
