# Generated by Django 5.1.3 on 2024-12-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LossHumanity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('average_value', models.IntegerField()),
                ('formula', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'loss_humanity',
            },
        ),
        migrations.CreateModel(
            name='ProgramClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'program_class',
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('takes_up_space', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'program_type',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.RenameModel(
            old_name='KeyWords',
            new_name='KeyWord',
        ),
        migrations.RenameModel(
            old_name='WeaponKeyWords',
            new_name='WeaponKeyWord',
        ),
        migrations.AlterModelOptions(
            name='itemtype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kindammo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modification',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pricecategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='source',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typeammo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='typekindammo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weaponammo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weaponkeyword',
            options={},
        ),
        migrations.RenameField(
            model_name='weaponkeyword',
            old_name='key_words',
            new_name='key_word',
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='modification',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pricecategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='typeammo',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.pricecategory'),
        ),
        migrations.AlterField(
            model_name='typekindammo',
            name='kind_ammo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.kindammo'),
        ),
        migrations.AlterField(
            model_name='typekindammo',
            name='type_ammo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.typeammo'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='magazine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='modifications_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='price_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.pricecategory'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='skill_need',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.source'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.itemtype'),
        ),
        migrations.AlterUniqueTogether(
            name='typekindammo',
            unique_together={('kind_ammo', 'type_ammo')},
        ),
        migrations.AlterUniqueTogether(
            name='weaponammo',
            unique_together={('weapon', 'kind_ammo')},
        ),
        migrations.AlterUniqueTogether(
            name='weaponkeyword',
            unique_together={('weapon', 'key_word')},
        ),
        migrations.CreateModel(
            name='Demon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('health', models.IntegerField()),
                ('interface', models.IntegerField()),
                ('network_actions', models.IntegerField()),
                ('combat_number', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.pricecategory')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.source')),
            ],
            options={
                'db_table': 'demon',
            },
        ),
        migrations.CreateModel(
            name='InstallationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'installation_location',
                'unique_together': {('name', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('occupies_slots', models.IntegerField(default=1)),
                ('requirements', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.pricecategory')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.source')),
                ('installation_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.installationlocation')),
                ('loss_humanity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.losshumanity')),
            ],
            options={
                'db_table': 'implants',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('perception', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('health', models.IntegerField()),
                ('price', models.IntegerField()),
                ('effect', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.pricecategory')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.source')),
                ('program_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.programclass')),
                ('program_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.programtype')),
            ],
            options={
                'db_table': 'program',
            },
        ),
        migrations.CreateModel(
            name='DefaultWeaponModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.modification')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.weapon')),
            ],
            options={
                'db_table': 'default_weapon_modification',
                'unique_together': {('weapon', 'modification')},
            },
        ),
        migrations.CreateModel(
            name='ImplantSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.implant')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.slot')),
            ],
            options={
                'db_table': 'implants_slot',
                'unique_together': {('implant', 'slot')},
            },
        ),
    ]
