# Generated by Django 5.1.1 on 2024-10-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapons_db',
            options={'verbose_name': 'Weapons_DB', 'verbose_name_plural': 'Weapons_DB'},
        ),
        migrations.RemoveField(
            model_name='weapons_db',
            name='price',
        ),
        migrations.AddField(
            model_name='weapons_db',
            name='price_high',
            field=models.CharField(default=None, max_length=50, verbose_name='Цена за отличное качество'),
        ),
        migrations.AddField(
            model_name='weapons_db',
            name='price_low',
            field=models.CharField(default=None, max_length=50, verbose_name='Цена за низкое качество'),
        ),
        migrations.AddField(
            model_name='weapons_db',
            name='price_mid',
            field=models.CharField(default=0, max_length=50, verbose_name='Цена за обычное качество'),
            preserve_default=False,
        ),
    ]
