# Generated by Django 5.1.1 on 2024-10-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_alter_weapons_db_options_remove_weapons_db_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons_db',
            name='able_to_hide',
            field=models.CharField(max_length=50, verbose_name='Можно скрыть?'),
        ),
    ]
