# Generated by Django 5.1.1 on 2024-10-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_alter_weapons_db_able_to_hide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapons_db',
            old_name='hands_needed',
            new_name='grab_type',
        ),
        migrations.RemoveField(
            model_name='weapons_db',
            name='able_to_hide',
        ),
        migrations.RemoveField(
            model_name='weapons_db',
            name='damage_1_shot',
        ),
        migrations.RemoveField(
            model_name='weapons_db',
            name='skill_needed',
        ),
        migrations.RemoveField(
            model_name='weapons_db',
            name='standard_mag',
        ),
        migrations.AddField(
            model_name='weapons_db',
            name='damage',
            field=models.CharField(max_length=100, null=True, verbose_name='Урон 1-го выстрела'),
        ),
        migrations.AddField(
            model_name='weapons_db',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Можно скрыть?'),
        ),
        migrations.AddField(
            model_name='weapons_db',
            name='magazine',
            field=models.CharField(max_length=50, null=True, verbose_name='Стандар. магазин'),
        ),
        migrations.AddField(
            model_name='weapons_db',
            name='skill_need',
            field=models.CharField(max_length=80, null=True, verbose_name='Навык'),
        ),
        migrations.AlterField(
            model_name='weapons_db',
            name='price_high',
            field=models.IntegerField(default=None, verbose_name='Цена за отличное качество'),
        ),
        migrations.AlterField(
            model_name='weapons_db',
            name='price_low',
            field=models.IntegerField(default=None, verbose_name='Цена за низкое качество'),
        ),
        migrations.AlterField(
            model_name='weapons_db',
            name='price_mid',
            field=models.IntegerField(verbose_name='Цена за обычное качество'),
        ),
        migrations.AlterField(
            model_name='weapons_db',
            name='rate_of_fire',
            field=models.IntegerField(verbose_name='СКА'),
        ),
    ]
