# Generated by Django 5.1.1 on 2024-10-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_rename_hands_needed_weapons_db_grab_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapons_db',
            name='price_high',
            field=models.IntegerField(default=None, null=True, verbose_name='Цена за отличное качество'),
        ),
        migrations.AlterField(
            model_name='weapons_db',
            name='price_low',
            field=models.IntegerField(default=None, null=True, verbose_name='Цена за низкое качество'),
        ),
        migrations.AlterField(
            model_name='weapons_db',
            name='price_mid',
            field=models.IntegerField(null=True, verbose_name='Цена за обычное качество'),
        ),
    ]
