# Generated by Django 5.1.1 on 2024-11-08 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_alter_weapons_db_price_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'item_type',
            },
        ),
        migrations.CreateModel(
            name='KeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'key_words',
            },
        ),
        migrations.CreateModel(
            name='KindAmmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('buy_count', models.IntegerField()),
            ],
            options={
                'db_table': 'kind_ammo',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'modification',
            },
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'price_category',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'source',
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TypeAmmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.pricecategory')),
            ],
            options={
                'db_table': 'type_ammo',
            },
        ),
        migrations.CreateModel(
            name='TypeKindAmmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_ammo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.kindammo')),
                ('type_ammo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.typeammo')),
            ],
            options={
                'db_table': 'type_kind_ammo',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
                ('is_exotic', models.BooleanField(default=False)),
                ('skill_need', models.TextField()),
                ('damage', models.IntegerField()),
                ('magazine', models.IntegerField()),
                ('rate_of_fire', models.IntegerField(default=2)),
                ('grab_type', models.IntegerField(default=1)),
                ('price_low', models.IntegerField(blank=True, null=True)),
                ('price_middle', models.IntegerField(blank=True, null=True)),
                ('price_high', models.IntegerField(blank=True, null=True)),
                ('unical_feature', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('modifications_count', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('price_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.pricecategory')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.source')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='references.itemtype')),
            ],
            options={
                'db_table': 'weapon',
            },
        ),
        migrations.CreateModel(
            name='WeaponAmmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_ammo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.kindammo')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.weapon')),
            ],
            options={
                'db_table': 'weapon_ammo',
            },
        ),
        migrations.CreateModel(
            name='WeaponKeyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.keywords')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.weapon')),
            ],
            options={
                'db_table': 'weapon_key_words',
            },
        ),
        migrations.DeleteModel(
            name='Weapons_DB',
        ),
    ]
